site_name: Путешествия по Великобритании
site_description: База знаний о путешествиях по Великобритании
docs_dir: travel-knowledge-base

theme:
  name: material
  language: ru
  custom_dir: docs_overrides
  font:
    text: Source Sans 3
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
  features:
    - navigation.top
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - поездки: uk/london-day-trips.md
  - Норидж: uk/norwich.md
  - Чичестер: uk/chichester.md
  - Борнмут и Пул: uk/борнмут-пул.md
  - Болье и Нью-Форест: uk/болье-нью-форест.md
  - Бат: uk/bath.md
  - парки: uk/london-walking-routes/index.md
